test: \
    test_clip \
    test_dateutil \
    test_distaz2lola \
    test_ff2gmt \
    test_fitutil \
    test_grid \
    test_lola2distaz \
    test_mtutil \
    test_o92util \
    test_platemotion \
    test_rangen \
    test_readGCMT \
    test_sphfinrot \
    test_stereo_project \
    test_surf_disp \
    test_trg_schem \
    test_triutil \
    test_vec2los \
    test_wraplos \
    test_fltinv

test_clip: test_clip.sh ../bin/clip test_values.sh
	test_clip.sh

test_dateutil: test_dateutil.sh ../bin/dateutil test_values.sh
	test_dateutil.sh

test_distaz2lola: test_distaz2lola.sh ../bin/distaz2lola test_values.sh
	test_distaz2lola.sh

test_ff2gmt: test_ff2gmt.sh ../bin/ff2gmt test_values.sh
	test_ff2gmt.sh

test_fitutil: test_fitutil.sh ../bin/fitutil test_values.sh
	test_fitutil.sh

test_grid: test_grid.sh ../bin/grid test_values.sh
	test_grid.sh

test_lola2distaz: test_lola2distaz.sh ../bin/lola2distaz test_values.sh
	test_lola2distaz.sh

test_mtutil: test_mtutil.sh ../bin/mtutil test_values.sh
	test_mtutil.sh

test_o92util: test_o92util.sh ../bin/o92util test_values.sh
	test_o92util.sh

test_platemotion: test_platemotion.sh ../bin/platemotion test_values.sh
	test_platemotion.sh

test_rangen: test_rangen.sh ../bin/rangen test_values.sh
	test_rangen.sh

test_readGCMT: test_readGCMT.sh ../bin/readGCMT test_values.sh
	test_readGCMT.sh

test_sphfinrot: test_sphfinrot.sh ../bin/sphfinrot test_values.sh
	test_sphfinrot.sh

test_stereo_project: test_stereo_project.sh ../bin/stereo_project test_values.sh
	test_stereo_project.sh

test_surf_disp: test_surf_disp.sh ../bin/surf_disp.sh test_values.sh
	test_surf_disp.sh

test_trg_schem: test_trg_schem.sh ../bin/trg_schem.sh test_values.sh
	test_trg_schem.sh

test_triutil: test_triutil.sh ../bin/triutil test_values.sh
	test_triutil.sh

test_vec2los: test_vec2los.sh ../bin/vec2los test_values.sh
	test_vec2los.sh

test_wraplos: test_wraplos.sh ../bin/wraplos test_values.sh
	test_wraplos.sh

test_fltinv: test_fltinv.sh ../bin/fltinv test_values.sh
	test_fltinv.sh
