##### Compilers #####
# C compiler
CC = gcc

# Fortran compiler
FC = gfortran

# Fortran compiler warnings
FWARN = -Wall -Wextra -Wunused -fbounds-check -fbacktrace
# FWARN =

# Fortran compiler optimization
# FOPT  =
FOPT  = -O1
# FOPT  = -O2

# Fortran compiler flags
FFLAGS = $(FWARN) $(FOPT)


##### Executable directory (where to put compiled codes and scripts) #####
BIN_DIR   = ./bin


##### Include directory (where to put .o and .mod files) #####
INCLUDE_DIR = ./include
INCLUDE_FLAGS = -I$(INCLUDE_DIR) -J$(INCLUDE_DIR)           # Include options


##### External libraries #####
# LAPACK (linear algebra)
LAPACK_LIB_DIR = /sw/lib/lapack                             # Path to LAPACK libraries

LAPACK_LIB     = -lreflapack -lrefblas -ltmglib             # Names of LAPACK libraries (may not
# LAPACK_LIB     = -llapack -lblas -ltmglib                 # have "ref" prefix)

LAPACK         = -L$(LAPACK_LIB_DIR) $(LAPACK_LIB)          # To compile with LAPACK, uncomment these lines
CPP_LAPACK     = -DUSE_LAPACK
# LAPACK         =                                            # To compile without LAPACK, uncomment these lines
# CPP_LAPACK     =

# SuperLU (sparse linear equation solvers)
SUPERLU_LIB_DIR = ./ext/SuperLU_5.2.1/lib
SUPERLU_LIB     = -lsuperlu_5.1
# SUPERLU         = -L$(SUPERLU_LIB_DIR) $(SUPERLU_LIB)
# CPP_SUPERLU = -DUSE_SUPERLU
SUPERLU =
CPP_SUPERLU =


##### Pre-processing #####
CPP_UNIT_TEST = -DUNIT_TEST
# CPP_UNIT_TEST =

CPP_FLAGS = -cpp $(CPP_UNIT_TEST) $(CPP_LAPACK) $(CPP_SUPERLU)



####################################################################################################
####################################################################################################
################### DO NOT CHANGE BELOW HERE UNLESS YOU KNOW WHAT YOU ARE DOING ####################
####################################################################################################
####################################################################################################

.PHONY: all scripts objects clean


##############################
##### HDEF PROGRAM RULES #####
##############################
all: \
    anneal_post \
    clip \
    colortool \
    dateutil \
    distaz2lola \
    ff2gmt \
    fitutil \
    fltinv \
    grid \
    lola2distaz \
    mtutil \
    numint \
    o92util \
    perspective \
    platemotion \
    rangen \
    readGCMT \
    readkik \
    sphfinrot \
    stereo_project \
    triutil \
    vec2los \
    wraplos \
    scripts

# Rules for compiled programs
anneal_post: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/anneal_post
$(BIN_DIR)/anneal_post: src/anneal_post.f90 \
                        $(INCLUDE_DIR)/algebra.o \
                        $(INCLUDE_DIR)/earth.o \
                        $(INCLUDE_DIR)/io.o
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ -o $@

clip: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/clip
$(BIN_DIR)/clip: src/clip.f90 \
                 $(INCLUDE_DIR)/algebra.o \
                 $(INCLUDE_DIR)/geom.o \
                 $(INCLUDE_DIR)/io.o
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ -o $@

colortool: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/colortool
$(BIN_DIR)/colortool: src/colortool.f90
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ -o $@

dateutil: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/dateutil
$(BIN_DIR)/dateutil: src/dateutil.f90 \
                     $(INCLUDE_DIR)/calendar.o \
                     $(INCLUDE_DIR)/io.o
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ -o $@

distaz2lola: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/distaz2lola
$(BIN_DIR)/distaz2lola: src/distaz2lola_prog.f90 \
                        $(INCLUDE_DIR)/algebra.o \
                        $(INCLUDE_DIR)/earth.o \
                        $(INCLUDE_DIR)/geom.o \
                        $(INCLUDE_DIR)/io.o
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ -o $@

ff2gmt: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/ff2gmt
$(BIN_DIR)/ff2gmt: src/ff2gmt.f90 \
                   $(INCLUDE_DIR)/algebra.o \
                   $(INCLUDE_DIR)/ffm.o \
                   $(INCLUDE_DIR)/geom.o \
                   $(INCLUDE_DIR)/io.o \
                   $(INCLUDE_DIR)/trig.o
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ -o $@

fitutil: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/fitutil
$(BIN_DIR)/fitutil: src/fitutil.f90 \
                    $(INCLUDE_DIR)/io.o \
                    $(INCLUDE_DIR)/solver.o \
                    $(INCLUDE_DIR)/trig.o
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ $(LAPACK) -o $@

fltinv: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/fltinv
$(BIN_DIR)/fltinv: src/fltinv.f90 \
                   src/fltinv_io.f90 \
                   src/fltinv_gf.f90 \
                   src/fltinv_lsqr.f90 \
                   src/fltinv_anneal.f90 \
                   src/fltinv_anneal_psc.f90 \
                   src/fltinv_anneal_psc_euler.f90 \
                   $(INCLUDE_DIR)/algebra.o \
                   $(INCLUDE_DIR)/annealing.o \
                   $(INCLUDE_DIR)/earth.o \
                   $(INCLUDE_DIR)/elast.o \
                   $(INCLUDE_DIR)/geom.o \
                   $(INCLUDE_DIR)/io.o \
                   $(INCLUDE_DIR)/okada92.o \
                   $(INCLUDE_DIR)/random.o \
                   $(INCLUDE_DIR)/solver.o \
                   $(INCLUDE_DIR)/trig.o \
                   $(INCLUDE_DIR)/tri_disloc.o
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ $(LAPACK) $(SUPERLU) -o $@

grid: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/grid
$(BIN_DIR)/grid: src/grid.f90 \
                 $(INCLUDE_DIR)/algebra.o \
                 $(INCLUDE_DIR)/earth.o \
                 $(INCLUDE_DIR)/geom.o \
                 $(INCLUDE_DIR)/io.o \
                 $(INCLUDE_DIR)/trig.o
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ -o $@

lola2distaz: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/lola2distaz
$(BIN_DIR)/lola2distaz: src/lola2distaz_prog.f90 \
                        $(INCLUDE_DIR)/algebra.o \
                        $(INCLUDE_DIR)/earth.o \
                        $(INCLUDE_DIR)/geom.o \
                        $(INCLUDE_DIR)/io.o
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ -o $@

mtutil: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/mtutil
$(BIN_DIR)/mtutil: src/mtutil.f90 \
                   $(INCLUDE_DIR)/eq.o \
                   $(INCLUDE_DIR)/io.o
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ $(LAPACK) -o $@

numint: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/numint
$(BIN_DIR)/numint: src/numint.f
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ -o $@

o92util: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/o92util
$(BIN_DIR)/o92util: src/o92util.f90 \
                    $(INCLUDE_DIR)/algebra.o \
                    $(INCLUDE_DIR)/earth.o \
                    $(INCLUDE_DIR)/elast.o \
                    $(INCLUDE_DIR)/eq.o \
                    $(INCLUDE_DIR)/ffm.o \
                    $(INCLUDE_DIR)/geom.o \
                    $(INCLUDE_DIR)/io.o \
                    $(INCLUDE_DIR)/okada92.o \
                    $(INCLUDE_DIR)/trig.o
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ $(LAPACK) -o $@

perspective: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/perspective
$(BIN_DIR)/perspective: src/perspective_prog.f90 \
                        $(INCLUDE_DIR)/algebra.o \
                        $(INCLUDE_DIR)/geom.o \
                        $(INCLUDE_DIR)/io.o
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ -o $@

platemotion: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/platemotion
$(BIN_DIR)/platemotion: src/platemotion.f90 \
                        $(INCLUDE_DIR)/algebra.o \
                        $(INCLUDE_DIR)/earth.o \
                        $(INCLUDE_DIR)/io.o \
                        $(INCLUDE_DIR)/trig.o
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ -o $@

rangen: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/rangen
$(BIN_DIR)/rangen: src/rangen.f90 \
                   $(INCLUDE_DIR)/io.o \
                   $(INCLUDE_DIR)/random.o
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ -o $@

readGCMT: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/readGCMT
$(BIN_DIR)/readGCMT: src/readGCMT.f90 \
                     $(INCLUDE_DIR)/algebra.o \
                     $(INCLUDE_DIR)/calendar.o \
                     $(INCLUDE_DIR)/earth.o \
                     $(INCLUDE_DIR)/eq.o \
                     $(INCLUDE_DIR)/geom.o \
                     $(INCLUDE_DIR)/io.o \
                     $(INCLUDE_DIR)/trig.o
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ $(LAPACK) -o $@

readkik: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/readkik
$(BIN_DIR)/readkik: src/readkik.f
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ $(LAPACK) -o $@

sphfinrot: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/sphfinrot
$(BIN_DIR)/sphfinrot: src/sphfinrot.f90 \
                      $(INCLUDE_DIR)/algebra.o \
                      $(INCLUDE_DIR)/earth.o \
                      $(INCLUDE_DIR)/io.o \
                      $(INCLUDE_DIR)/trig.o
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ -o $@

stereo_project: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/stereo_project
$(BIN_DIR)/stereo_project: src/stereo_project.f90 \
                           $(INCLUDE_DIR)/algebra.o \
                           $(INCLUDE_DIR)/earth.o \
                           $(INCLUDE_DIR)/io.o \
                           $(INCLUDE_DIR)/map.o
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ -o $@

triutil: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/triutil
$(BIN_DIR)/triutil: src/triutil.f90 \
                    $(INCLUDE_DIR)/algebra.o \
                    $(INCLUDE_DIR)/geom.o \
                    $(INCLUDE_DIR)/earth.o \
                    $(INCLUDE_DIR)/elast.o \
                    $(INCLUDE_DIR)/eq.o \
                    $(INCLUDE_DIR)/geom.o \
                    $(INCLUDE_DIR)/io.o \
                    $(INCLUDE_DIR)/trig.o \
                    $(INCLUDE_DIR)/tri_disloc.o
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ $(LAPACK) -o $@

vec2los: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/vec2los
$(BIN_DIR)/vec2los: src/vec2los.f90 \
                    $(INCLUDE_DIR)/io.o \
                    $(INCLUDE_DIR)/trig.o
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ -o $@

wraplos: $(BIN_DIR_MARKER_FILE) $(BIN_DIR)/wraplos
$(BIN_DIR)/wraplos: src/wraplos.f90 \
                    $(INCLUDE_DIR)/io.o \
                    $(INCLUDE_DIR)/trig.o
	$(FC) $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $^ -o $@


# Rules for scripts
scripts: \
    $(BIN_DIR)/coul_dip.sh \
    $(BIN_DIR)/coul_hor.sh \
    $(BIN_DIR)/coul_xsec.sh \
    $(BIN_DIR)/gmtcpt.sh \
    $(BIN_DIR)/simplify_ffm.sh \
    $(BIN_DIR)/surf_disp.sh \
    $(BIN_DIR)/ternary.sh \
    $(BIN_DIR)/trg_schem.sh

$(BIN_DIR)/coul_dip.sh: ./scripts/coul_dip.sh $(BIN_DIR_MARKER_FILE)
	cp $< $@
$(BIN_DIR)/coul_hor.sh: ./scripts/coul_hor.sh $(BIN_DIR_MARKER_FILE)
	cp $< $@
$(BIN_DIR)/coul_xsec.sh: ./scripts/coul_xsec.sh $(BIN_DIR_MARKER_FILE)
	cp $< $@
$(BIN_DIR)/gmtcpt.sh: ./scripts/gmtcpt.sh $(BIN_DIR_MARKER_FILE)
	cp $< $@
$(BIN_DIR)/simplify_ffm.sh: ./scripts/simplify_ffm.sh $(BIN_DIR_MARKER_FILE)
	cp $< $@
$(BIN_DIR)/surf_disp.sh: ./scripts/surf_disp.sh $(BIN_DIR_MARKER_FILE)
	cp $< $@
$(BIN_DIR)/ternary.sh: ./scripts/ternary.sh $(BIN_DIR_MARKER_FILE)
	cp $< $@
$(BIN_DIR)/trg_schem.sh: ./scripts/trg_schem.sh $(BIN_DIR_MARKER_FILE)
	cp $< $@




####################################
##### MODULE AND OBJECT RULES ######
####################################
$(INCLUDE_DIR)/algebra.o: src/algebra_module.f90 \
                          $(INCLUDE_DIR)/io.o \
                          $(INCLUDE_DIR)/trig.o \
                         $(INCLUDE_DIR_MARKER_FILE)
	$(FC) $(FFLAGS) -J$(INCLUDE_DIR) $(CPP_FLAGS) $< -c -o $@

$(INCLUDE_DIR)/annealing.o: src/annealing_module.f90 \
                            $(INCLUDE_DIR)/io.o \
                            $(INCLUDE_DIR)/random.o \
                            $(INCLUDE_DIR_MARKER_FILE)
	$(FC) $(FFLAGS) -J$(INCLUDE_DIR) $(CPP_FLAGS) $< -c -o $@

$(INCLUDE_DIR)/calendar.o: src/calendar_module.f90 \
                           $(INCLUDE_DIR)/io.o \
                           $(INCLUDE_DIR_MARKER_FILE)
	$(FC) $(FFLAGS) -J$(INCLUDE_DIR) $(CPP_FLAGS) $< -c -o $@

$(INCLUDE_DIR)/earth.o: src/earth_module.f90 \
                        $(INCLUDE_DIR)/algebra.o \
                        $(INCLUDE_DIR)/io.o \
                        $(INCLUDE_DIR)/trig.o \
                        $(INCLUDE_DIR_MARKER_FILE)
	$(FC) $(FFLAGS) -J$(INCLUDE_DIR) $(CPP_FLAGS) $< -c -o $@

$(INCLUDE_DIR)/elast.o: src/elast_module.f90 \
                        $(INCLUDE_DIR)/algebra.o \
                        $(INCLUDE_DIR)/geom.o \
                        $(INCLUDE_DIR)/io.o \
                        $(INCLUDE_DIR_MARKER_FILE)
	$(FC) $(FFLAGS) -J$(INCLUDE_DIR) $(CPP_FLAGS) $(LAPACK) $< -c -o $@

$(INCLUDE_DIR)/eq.o: src/eq_module.f90 \
                     $(INCLUDE_DIR)/io.o \
                     $(INCLUDE_DIR)/trig.o \
                     $(INCLUDE_DIR_MARKER_FILE)
	$(FC) $(FFLAGS) -J$(INCLUDE_DIR) $(CPP_FLAGS) $(LAPACK) $< -c -o $@

$(INCLUDE_DIR)/error_exit.o: src/error_exit.c \
                             $(INCLUDE_DIR_MARKER_FILE)
	$(CC) $<  -c -o $@

$(INCLUDE_DIR)/ffm.o: src/ffm_module.f90 \
                      $(INCLUDE_DIR)/geom.o \
                      $(INCLUDE_DIR)/io.o \
                      $(INCLUDE_DIR)/trig.o \
                      $(INCLUDE_DIR_MARKER_FILE)
	$(FC) $(FFLAGS) -J$(INCLUDE_DIR) $(CPP_FLAGS) $< -c -o $@

$(INCLUDE_DIR)/geom.o: src/geom_module.f90 \
                       $(INCLUDE_DIR)/algebra.o \
                       $(INCLUDE_DIR)/io.o \
                       $(INCLUDE_DIR)/trig.o \
                       $(INCLUDE_DIR_MARKER_FILE)
	$(FC) $(FFLAGS) -J$(INCLUDE_DIR) $(CPP_FLAGS) $< -c -o $@

$(INCLUDE_DIR)/io.o: src/io_module.f90 \
                     $(INCLUDE_DIR_MARKER_FILE)
	$(FC) $(FFLAGS) -J$(INCLUDE_DIR) $(CPP_FLAGS) $< -c -o $@

$(INCLUDE_DIR)/okada92.o: src/okada92_module.f90 \
                          $(INCLUDE_DIR)/io.o \
                          $(INCLUDE_DIR)/trig.o \
                          $(INCLUDE_DIR_MARKER_FILE)
	$(FC) $(FFLAGS) -J$(INCLUDE_DIR) $(CPP_FLAGS) $< -c -o $@

$(INCLUDE_DIR)/map.o: src/map_module.f90 \
                      $(INCLUDE_DIR)/earth.o \
                      $(INCLUDE_DIR)/io.o \
                      $(INCLUDE_DIR)/trig.o \
                      $(INCLUDE_DIR_MARKER_FILE)
	$(FC) $(FFLAGS) -J$(INCLUDE_DIR) $(CPP_FLAGS) $< -c -o $@

$(INCLUDE_DIR)/random.o: src/random_module.f90 \
                     $(INCLUDE_DIR_MARKER_FILE)
	$(FC) $(FFLAGS) -J$(INCLUDE_DIR) $(CPP_FLAGS) $(LAPACK) $< -c -o $@

$(INCLUDE_DIR)/solver.o: src/solver_module.f90 \
                         $(INCLUDE_DIR)/io.o \
                         $(INCLUDE_DIR_MARKER_FILE)
	$(FC) $(FFLAGS) -J$(INCLUDE_DIR) $(CPP_FLAGS) $(LAPACK) $< -c -o $@

$(INCLUDE_DIR)/test.o: src/test_module.f90 \
                       $(INCLUDE_DIR)/error_exit.o \
                       $(INCLUDE_DIR_MARKER_FILE)
	$(FC) $(FFLAGS) -J$(INCLUDE_DIR) $(CPP_FLAGS) $< -c -o $@

$(INCLUDE_DIR)/trig.o: src/trig_module.f90 \
                     $(INCLUDE_DIR_MARKER_FILE)
	$(FC) $(FFLAGS) -J$(INCLUDE_DIR) $(CPP_FLAGS) $< -c -o $@

$(INCLUDE_DIR)/tri_disloc.o: src/tri_disloc_module.f90 \
                             $(INCLUDE_DIR)/earth.o \
                             $(INCLUDE_DIR)/geom.o \
                             $(INCLUDE_DIR)/io.o \
                             $(INCLUDE_DIR)/trig.o \
                             $(INCLUDE_DIR_MARKER_FILE)
	$(FC) $(FFLAGS) -J$(INCLUDE_DIR) $(CPP_FLAGS) $< -c -o $@

$(INCLUDE_DIR)/%.o: $(INCLUDE_DIR)/%.mod



##################################
##### DIRECTORY MARKER FILES #####
##################################
# Marker files to indicate that directories have been made/updated
BIN_DIR_MARKER_FILE = $(BIN_DIR)/.readme
$(BIN_DIR_MARKER_FILE):
	mkdir -p $(BIN_DIR)
	date +%Y-%m-%dT%H:%M:%S > $(BIN_DIR_MARKER_FILE)

INCLUDE_DIR_MARKER_FILE = $(INCLUDE_DIR)/.readme
$(INCLUDE_DIR_MARKER_FILE):
	mkdir -p $(INCLUDE_DIR)
	date +%Y-%m-%dT%H:%M:%S > $(INCLUDE_DIR_MARKER_FILE)




###########################
##### UNIT TEST RULES #####
###########################
test: \
      test_annealing \
      test_calendar \
      test_earth \
      test_eq \
      test_ffm \
      test_geom \
      test_map \
      test_okada92 \
      test_random \
      test_solver \
      test_tri_disloc \
      test_executables

test_annealing: src/unit_test_annealing.f90 \
                $(INCLUDE_DIR)/annealing.o \
                $(INCLUDE_DIR)/random.o \
                $(INCLUDE_DIR)/test.o \
                $(INCLUDE_DIR)/error_exit.o \
                $(INCLUDE_DIR)/io.o
	@$(FC) $^ $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) -o $@
	$@ > test_annealing.log
	@echo "test_annealing passed"
	rm $@ test_annealing.log include/driver*.mod
	@echo

test_calendar: src/unit_test_calendar.f90 \
               $(INCLUDE_DIR)/calendar.o \
               $(INCLUDE_DIR)/test.o \
               $(INCLUDE_DIR)/error_exit.o \
               $(INCLUDE_DIR)/io.o
	@$(FC) $^ $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) -o $@
	$@ > test_calendar.log
	@echo "test_calendar passed"
	rm $@ test_calendar.log
	@echo

test_earth: src/unit_test_earth.f90 \
            $(INCLUDE_DIR)/algebra.o \
            $(INCLUDE_DIR)/earth.o \
            $(INCLUDE_DIR)/test.o \
            $(INCLUDE_DIR)/error_exit.o \
            $(INCLUDE_DIR)/io.o \
            $(INCLUDE_DIR)/trig.o
	@$(FC) $^ $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $(LAPACK) -o $@
	$@ > test_earth.log
	@echo "test_earth passed"
	rm $@ test_earth.log
	@echo

test_eq: src/unit_test_eq.f90 \
         $(INCLUDE_DIR)/eq.o \
         $(INCLUDE_DIR)/test.o \
         $(INCLUDE_DIR)/error_exit.o \
         $(INCLUDE_DIR)/io.o
	@$(FC) $^ $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $(LAPACK) -o $@
	$@ > test_eq.log
	@echo "test_eq passed"
	rm $@ test_eq.log
	@echo

test_executables: all
	cd ./test/ && make test

test_ffm: src/unit_test_ffm.f90 \
          $(INCLUDE_DIR)/algebra.o \
          $(INCLUDE_DIR)/ffm.o \
          $(INCLUDE_DIR)/geom.o \
          $(INCLUDE_DIR)/test.o \
          $(INCLUDE_DIR)/error_exit.o \
          $(INCLUDE_DIR)/io.o
	@$(FC) -ffree-line-length-0 $^ $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) -o $@
	$@ > test_ffm.log
	@echo "test_ffm passed"
	rm $@ test_ffm.log
	@echo

test_geom: src/unit_test_geom.f90 \
           $(INCLUDE_DIR)/algebra.o \
           $(INCLUDE_DIR)/geom.o \
           $(INCLUDE_DIR)/test.o \
           $(INCLUDE_DIR)/error_exit.o \
           $(INCLUDE_DIR)/io.o
	@$(FC) $^ $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) -o $@
	$@ > test_geom.log
	@echo "test_geom passed"
	rm $@ test_geom.log
	@echo

test_map: src/unit_test_map.f90 \
           $(INCLUDE_DIR)/test.o \
           $(INCLUDE_DIR)/error_exit.o \
           $(INCLUDE_DIR)/io.o \
           $(INCLUDE_DIR)/map.o
	@$(FC) $^ $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) -o $@
	$@ > test_map.log
	@echo "test_map passed"
	rm $@ test_map.log
	@echo

test_okada92: src/unit_test_okada92.f90 \
              $(INCLUDE_DIR)/okada92.o \
              $(INCLUDE_DIR)/test.o \
              $(INCLUDE_DIR)/trig.o \
              $(INCLUDE_DIR)/error_exit.o \
              $(INCLUDE_DIR)/io.o
	@$(FC) $^ $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) -o $@
	$@ > test_okada92.log
	@echo "test_okada92 passed"
	rm $@ test_okada92.log
	@echo

test_random: src/unit_test_random.f90 \
             $(INCLUDE_DIR)/random.o \
             $(INCLUDE_DIR)/test.o \
             $(INCLUDE_DIR)/error_exit.o \
             $(INCLUDE_DIR)/io.o
	@$(FC) $^ $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) -o $@
	$@ > test_random.log
	@echo "test_random passed"
	rm $@ test_random.log
	@echo

test_solver: src/unit_test_solver.f90 \
             $(INCLUDE_DIR)/solver.o \
             $(INCLUDE_DIR)/test.o \
             $(INCLUDE_DIR)/error_exit.o \
             $(INCLUDE_DIR)/io.o
	@$(FC) $^ $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) $(LAPACK) $(SUPERLU) -o $@
	$@ > test_solver.log
	@echo "test_solver passed"
	rm $@ test_solver.log
	@echo

test_tri_disloc: src/unit_test_tri_disloc.f90 \
                 $(INCLUDE_DIR)/algebra.o \
                 $(INCLUDE_DIR)/tri_disloc.o \
                 $(INCLUDE_DIR)/geom.o \
                 $(INCLUDE_DIR)/test.o \
                 $(INCLUDE_DIR)/trig.o \
                 $(INCLUDE_DIR)/error_exit.o \
                 $(INCLUDE_DIR)/io.o
	@$(FC) $^ $(FFLAGS) $(INCLUDE_FLAGS) $(CPP_FLAGS) -o $@
	$@ > test_tri_disloc.log
	@echo "test_tri_disloc passed"
	rm $@ test_tri_disloc.log
	@echo

####################
##### CLEAN UP #####
####################
# Clean bin directory
clean:
	-rm $(BIN_DIR)/*
	-rm $(INCLUDE_DIR)/*
