.TH FLTINV 1 "Sep 2018" "Version 2018.09.16" "User Manuals"

.SH NAME
fltinv \- invert displacement or pre-stresses for fault slip.

.SH SYNOPSIS
.P
.B fltinv ...options...

.SH DESCRIPTION
.B fltinv
inverts for fault slip distributions based on either displacement observations
or pre-stresses resolved onto the faults. The inversion can be done using linear least
squares, simulated annealing, or the neighborhood algorithm. The inputs are the same for
all of the inversion modes, but the outputs can change depending on command line
specifications.




.SH OPTIONS




.TP
.BI "-mode " inversion_mode
Specify the
.IR inversion_mode :
.BR lsqr " (default), " anneal ", or " anneal-psc .

.BR lsqr :
Linear least-squares inversion. Loads Green's functions, damping, and smoothing
into model matrix, and corresponding constraints into observation vector. Uses
dgels (LAPACK generalized least squares) or nnls (Non-negative least-squares)
algorithm to invert for fault slip values.

.BR anneal :
Simulated annealing inversion. Starts with an initial fault solution, then
randomly perturbs fault slip and rake values. If objective function
(sum of RMS misfit, total shear stress, model length, and roughness) decreases,
keeps new solution. If objective increases, keeps new solution with a probability
that decreases over the search (associated with the "temperature" of the annealing
process). For more information, see Sambridge and Mosegaard (2002).

.BR anneal-psc :
Simulated annealing inversion with pseudo-coupling as defined by Herman et al. (2018).
Starts with all faults unlocked, then randomly switches subset of faults from unlocked
to locked or vice versa. Computes partial slip around locked sections using least squares
and calculates corresponding misfit to displacement observations.

.TP
.B OUTPUT OPTIONS
.TP
.BI "-o " output_file
By default,
.B fltinv
prints the solution to standard output. To redirect the solution to a file, use the
.B -o
option. The solution has the format:
.IR "strike-slip dip-slip" ,
for each fault in the input
.IR fault_file ,
including faults with fixed slip values.

.TP
.B INPUT OPTIONS
.TP
.BI "-disp " displacement_file
Three-component displacement observations in the format:
.IR "x y z ux uy uz" .
The misfit between these displacements and those produced by modeled fault slip will be minimized.
All values are in SI units, unless the coordinate type is changed to geographic using the
.B -geo
option.

.TP
.BI "-disp:components [" 1 ][ 2 ][ 3 ]
Use only selected displacement components in the inversion. Default is
.IR 123 .
Useful when only horizontal or vertical data are available or in 2D problems.

.TP
.BI "-disp:misfit " misfit_file
Print RMS misfit to displacements to file
.IR misfit_file .

.TP
.BI "-los " los_file
Line-of-sight displacement observations in the format:
.IR "x y z ulos azimuth inclination" .
.I Azimuth
is the look direction for the observation, clockwise from north.
.I Inclination
is the vertical look direction for the observation, from 0 at the horizon to 90 at vertical.
The misfit between these displacements and those produced by modeled fault slip will be minimized.
All values are in SI units, unless the coordinate type is changed to geographic using the
.B -geo
option, and angles are in degrees.

.TP
.BI "-los:weight " weight
Set the weight for the minimizing fit to line-of-sight observations
part of the inversion (default: 1)

.TP
.BI "-los:misfit " misfit_file
Print RMS misfit to line-of-sight displacements to file
.IR misfit_file .

.TP
.BI "-prests " prestress_file
Pre-stresses on all input faults in the format:
.IR "sxx syy szz sxy sxz syz" .
The shear stresses resolved onto the faults will be minimized - note that
the pre-stress values can be set to zero to minimize shear stresses without
external influences. All values are in SI units.

.TP
.BI "-prests:weight " weight
Set the weight for the minimizing stress part of the inversion (default: 1e-9)

.TP
.BI "-flt " fault_file
File containing parameters of faults for inversion. The file format depends on the
Green's function calculation model type, specified using option
.BR -gf:model :

.BR okada_rect :
.I x y z str dip wid len
.br
.BR okada_pt :
.I x y z str dip area

The
.I fault_file
needs to be in its full format if GFs must be computed for either displacements or stresses.
All values are in SI units. If all desired GFs are pre-computed (options
.BR -gf:disp_file " or " -gf:sts_file ),
this file can contain anything as long as the number of lines corresponds to the number of
faults for the GFs.

.TP
.BI "-flt:rake " rake_constraint_file
Constraints on the rake angles. File format and meaning depends on value of
.IR inversion_mode :

.BR lsqr :
.I fixed_rake
(set fault rake angles to fixed values;
if one column, set rakes to that fixed value;
if two columns, do two-component slip inversion with these rakes instead of 0 and 90 -
this is useful for constraining rake to one quadrant in conjunction with
.BR nnls )
.br
.BR anneal :
.I rake_min rake_max
(defines the range of possible rake angles)

If
.I rake_constraint_file
has only one line, use that value for all faults. Otherwise, the rake angles in the file
must correspond to the faults in
.IR fault_file .

.TP
.BI "-flt:slip " slip_constraint_file
Constraints on the slip magnitudes. File format and meaning depends on value of
.IR inversion_mode :

.BR lsqr :
.I strike_slip dip_slip
(set fault slip to fixed values; set to 99999 to NOT fix the value)
.br
.BR anneal :
.I slip_min slip_max
(defines the range of possible slip magnitudes)

If
.I slip_constraint_file
has only one line, use that value for all faults. Otherwise, slip magnitudes in the file
must correspond to the faults in
.IR fault_file .




.TP
.B GREENS FUNCTIONS OPTIONS
.TP
.BI "-gf:model " model
Model to be used to calculate Green's functions:
.BR okada_rect " (default) or " okada_pt .

.TP
.BI "-gf:disp_file " gf_disp_file
Pre-computed displacement Green's functions, e.g., from a finite element model.
All values are in SI units.
The file structure is as follows:

       1 - m  |  1 - m
.br
     _________|_________
.br
    [         |         ]
.br
  1 [         |         ]
.br
  | [  ux_ss  |  ux_ds  ]
.br
  n [         |         ]
.br
 ___[_________|_________]
.br
    [         |         ]
.br
  1 [         |         ]
.br
  | [  uy_ss  |  uy_ds  ]
.br
  n [         |         ]
.br
 ___[_________|_________]
.br
    [         |         ]
.br
  1 [         |         ]
.br
  | [  uz_ss  |  uz_ds  ]
.br
  n [         |         ]
.br
    [_________|_________]

where n is the number of displacement observations, m is the number of faults,
ux, uy, uz are the components of displacement, and ss and ds are strike-slip
and dip-slip fault sources.

.TP
.BI "-gf:stress_file " gf_stress_file
Pre-computed stress Green's functions, e.g., from a finite element model.
All values are in SI units.
The file structure is as follows:

       1 - m  |  1 - m
.br
     _________|_________
.br
    [         |         ]
.br
  1 [ ss sts  | ss sts  ]
.br
  | [    /    |    /    ]
.br
  m [  ss slp |  ds slp ]
.br
 ___[_________|_________]
.br
    [         |         ]
.br
  1 [ ds sts  | ds sts  ]
.br
  | [    /    |    /    ]
.br
  m [  ss slp |  ds slp ]
.br
    [_________|_________]

where m is the number of faults, ss sts and ds sts are the strike-slip and dip-slip
components of the shear traction resolved onto the fault plane, and ss slp and ds slp
are strike-slip and dip-slip fault sources.




.TP
.B INVERSION OPTIONS

.TP
.BI "-damping " damping_constant
Minimize the L1 length of the fault slip solution with a weighting factor of
.IR damping_constant * damping_constant

.TP
.BI "-smoothing " "smoothing_constant smoothing_file"
Minimize the Laplacian roughness of the fault slip solution with a weighting factor of
.IR smoothing_constant * smoothing_constant .
The file
.I smoothing_file
describes the connectivity between fault segments and has the following format:

ifault nneighbors neighbor_1 neighbor_2 ... neighbor_n




.TP
.B MISCELLANEOUS OPTIONS

.TP
.B "-geo"
Treat
.I x
and
.I y
as geographic coordinates instead of SI units in
.IR fault_file " and " displacement_file .

.TP
.BI "-haf " "halfspace_file [flag]"
Define the elastic half-space parameters for gf:model
.B okada_rect
or
.BR okada_pt .
By default, this file contains vp (m/s), vs (m/s), and density (kg/m^3).
At some point, you will be able to specify the elastic parameters in the file
with the
.I flag
option, but not yet.

.TP
.BI "-v " level
Set the verbosity of the program. Level 1 prints major steps, level 2 prints subroutine
start/finish, and level 3 prints all intermediate calculations.



.TP
.B LEAST SQUARES OPTIONS

.TP
.BI "-lsqr:mode " gels | nnls
Set the algorithm to use for the least-squares solution (default: gels).
The gels algorithm is from the LAPACK library.
The nnls algorithm is from Lawson and Hanson (1974), translated into Fortran 90
by Alan Miller.


.TP
.B SIMULATED ANNEALING OPTIONS

.TP
.BI "-anneal:init_mode " mean | zero | rand
Set the mode to initialize the slip and rake values of the solution (default: mean):

.BR mean :
set values to middle of ranges set in
.I slip_constraint_file
and
.I rake_constraint_file
.br
.BR zero :
set values to zero
.br
.BR rand :
set values to random within ranges set in
.I slip_constraint_file
and
.I rake_constraint_file
.br

.TP
.BI "-anneal:it_max " max_iteration
Set the maximum number of iterations in the simulated annealing search
(default: 1000).

.TP
.BI "-anneal:it_reset " reset_iteration
After each
.I reset_iteration
steps, the current solution will be set to the best solution and the
temperature will be set to
.I temp_start
(default: 1000000).

.TP
.BI "-anneal:log_file " anneal_log_file
Keep a log of current solutions in
.IR anneal_log_file .

.TP
.BI "-anneal:temp_0 " temp_start
Starting temperature for annealing process (default: 2).
Positive
.I temp_start
will use this value as a scaling factor, multiplied by the objective function
corresponding to the initial solution.
Negative
.I temp_start
will use the absolute value as the initial temperature.
High temperatures lead to all solutions being accepted, i.e., a random search.
Low temperatures lead to only better solutions being accepted, i.e. a gradient search.

.TP
.BI "-anneal:temp_min " temp_minimum
Minimum temperature for annealing process (default: 0).
Positive
.I temp_minimum
will use this value as a scaling factor, multiplied by the objective function
corresponding to the initial solution.
Negative
.I temp_minimum
will use the absolute value as the minimum temperature.

.TP
.BI "-anneal:cool " cooling_factor
Factor to reduce temperature by every iteration (default: 0.98).




.SH REFERENCES
Herman, M.W., Furlong, K.P., Govers, R. (2018).
The accumulation of slip deficit in subduction zones in the absence of mechanical
coupling: Implications for the behavior of megathrust earthquakes.

Sambridge, Mosegaard (2002). Monte Carlo Methods in Geophysical Inverse Problems.
.RS
