.TH SURF_DISP.SH 1 "March 2018" "Version 2018.03.01" "User Manuals"

.SH NAME
surf_disp.sh \- plot surface displacements for a fault source

.SH SYNOPSIS
.P
.B surf_disp.sh
.I source_type source_file
.BI [...]

.SH DESCRIPTION
.B surf_disp.sh
computes displacement vectors for an earthquake source embedded in an elastic
half-space and plots them on a map, with vertical displacements contoured as
colors and horizontal displacements shown as vectors.

.SH OPTIONS
.TP
.I source_type
Choose from a moment tensor 
.IR "" " (" MT )
or finite fault model source in standard USGS subfault format
.IR "" " (" FFM )
or SRCMOD FSP format
.IR "" " (" FSP ).
For the 
.I MT
option, the input file has the format:
.I evlo evla evdp str dip rak
.IR mag .
.TP
.I source_file
Name of fault source file
.TP
.BI -R west / east / south / north
Map limits (default defines limits automatically)
.TP
.BI -T vmin / vmax / dv
Vertical displacement color palette range (default defines color palette automatically)
.TP
.BI -nvert " nvert"
Number of points along one dimension for background vertical displacement contour
(default: 100)
.TP
.BI -nvec " nvec"
Number of points along one dimension for horizontal displacement vector grid
(default: 20)
.TP
.B -seg
Plot finite fault segments individually (default plots outline surrounding all segments)
.TP
.B -getscript
Copy script
.B surf_disp.sh
to current working directory (useful for manually editing script)
.TP
.B -novector
Suppress plotting of horizontal displacement vectors
.TP
.BI -o " output_file"
Basename for output file. Script produces
.IR output_file ".ps and " output_file .pdf
(default: surf_disp)
.TP
.BI -gps " gps_file"
Plot observed GPS displacements and predicted displacements at GPS stations.
Suppresses grid of displacements. Input file format:
.I stlo stla disp_east disp_north disp_vertical
.TP
.BI -vecscale " vector_scale"
Scale vectors by
.I vector_scale
inches (default automatically scales vectors)
.TP
.BI -veclbl " vector_label"
Define length of vector in legend

.RS
