#!/bin/sh

###############################################################################
# Script for computing and plotting Coulomb stress changes on a dipping
# surface generated by an earthquake in an elastic half-space.
###############################################################################

gmt set PS_MEDIA letter

if [ ! -f no_green_mwh.cpt ]; then
cat > no_green_mwh.cpt << EOF
# Color table using in Lab for Satellite Altimetry
# For folks who hate green in their color tables
# Designed by W.H.F. Smith, NOAA
# Modified to make small values white
-32     32/96/255       -28     32/96/255
-28     32/159/255      -24     32/159/255
-24     32/191/255      -20     32/191/255
-20     0/207/255       -16     0/207/255
-16     42/255/255      -12     42/255/255
-12     85/255/255      -8      85/255/255
-8      127/255/255     -3.2    127/255/255
-3.2    255/255/255     0       255/255/255
0       255/255/255     3.2     255/255/255
3.2     255/240/0       8       255/240/0
8       255/191/0       12      255/191/0
12      255/168/0       16      255/168/0
16      255/138/0       20      255/138/0
20      255/112/0       24      255/112/0
24      255/77/0        28      255/77/0
28      255/0/0         32      255/0/0
B       32/96/255
F       255/0/0
EOF
fi

###############################################################################
# The user can specify the following variables:
#  PSFILE   Name of the output PostScript file
#  NN       Density of the computation grid (NN x NN)
#  THR      Threshold value for slip in FFM (fraction of maximum slip)
###############################################################################

# Name of output PostScript file
PSFILE="coul_dip.ps"

# Coulomb stress grid is (NN x NN) points
NN="150"
#NN="50"

# Threshold percentage of peak slip in FFM to be retained
THR="0.15"

###############################################################################
#	PARSE COMMAND LINE TO GET SOURCE TYPE AND FILE NAME
###############################################################################

function USAGE() {
echo
echo "Usage: coul_dip.sh SRC_TYPE SRC_FILE [-Rw/e/s/n] [-Ts/d/r] [-Plo/la/dp] [-seg]"
echo "    SRC_TYPE     Either MT (moment tensor) or FFM (finite fault model)"
echo "    SRC_FILE     Name of input file"
echo "                   MT:  EVLO EVLA EVDP STR DIP RAK MAG"
echo "                   FFM: finite fault model in subfault format"
echo "    -Rw/e/s/n    Define map limits (optional)"
echo "    -Ts/d/r      Define target fault strike/dip/rake (optional)"
echo "    -Plo/la/dp   Define reference point for dipping grid (optional)"
echo "    -seg         Draw each fault segment (default draws as one segment)"
echo 
exit
}
# Check for minimum number of required arguments
if [ $# -lt 2 ]
then
    echo "!! Error: SRC_TYPE and SRC_FILE arguments required"
    echo "!!        Other arguments optional"
    USAGE
fi
SRC_TYPE="$1"
SRC_FILE="$2"
# Check that source type is correct
if [ $SRC_TYPE != "FFM" -a $SRC_TYPE != "MT" ]
then
    echo "!! Error: source type must be FFM or MT"
    USAGE
fi
# Check that input file exists
if [ ! -f $SRC_FILE ]
then
    echo "!! Error: no source file $SRC_FILE found"
    USAGE
fi
# Parse optional arguments
LIMS=""
TSTR=""
TDIP=""
TRAK=""
LON0=""
LAT0=""
Z0=""
SEG="0"
shift;shift
while [ "$1" != "" ]
do
    case $1 in
        -R*) LIMS="$1"
             ;;
        -T*) TSTR=`echo $1 | sed -e "s/-T//" | awk -F"/" '{print $1}'`
             TDIP=`echo $1 | sed -e "s/-T//" | awk -F"/" '{print $2}'`
             TRAK=`echo $1 | sed -e "s/-T//" | awk -F"/" '{print $3}'`
             ;;
        -P*) LON0=`echo $1 | sed -e "s/-P//" | awk -F"/" '{print $1}'`
             LAT0=`echo $1 | sed -e "s/-P//" | awk -F"/" '{print $2}'`
             Z0=`echo $1 | sed -e "s/-P//" | awk -F"/" '{print $3}'`
             ;;
        -seg) SEG="1" ;;
          *) echo "!! Error: no option \"$1\""
             USAGE
             ;;
    esac
    shift
done

###############################################################################
###############################################################################
# Everything below this point should be automated. This script requires the
# tools O92UTIL, GRID, and FF2GMT from Matt's codes, and creates the figure
# using GMT 5 commands. All of the work is performed in the same directory
# that the script is run from.
###############################################################################
###############################################################################

#####
#       INPUT FILES FOR COULOMB STRESS CALCULATION
#####
if [ $SRC_TYPE == "FFM" ]
then
    # Copy FFM to new file name
    cp $SRC_FILE ./ffm.dat
    # Simplify FFM by removing slip smaller than minimum threshold
    # percentage of maximum slip (THR*MAXSLIP)
    MAXSLIP=`awk '{if(substr($1,1,1)!="#" && NF>3){print $4}}' ffm.dat |\
             gmtinfo -C -I0.01 | awk '{print $2}'`
    awk '{
      if (substr($1,1,1)!="#" && NF>3 && $4<'"$MAXSLIP"'*'"$THR"')
        {print $1,$2,$3,0,$5,$6,$7,$8,$9,$10,$11}
      else
        {print $0}
    }' ffm.dat > t
    mv t ffm.dat
else
    # Copy MT to new file name
    cp $SRC_FILE ./mt.dat
fi

# Elastic half-space properties
LAMDA="4e10" # Lame parameter
MU="4e10"    # Shear modulus
echo "Lame $LAMDA $MU" > haf.dat

# Target fault depth and geometry, orientation and reference point of dipping grid
if [ $SRC_TYPE == "FFM" ]
then
    # Use peak slip patch for automatic kinematics
    MAXLN=`awk 'BEGIN{max=0}
             {if(substr($1,1,1)!="#"&&NF>3){if($4>max){max=$4;line=NR}}}
             END{print line}' ffm.dat`
    if [ -z $TRAK ]
    then
        TSTR=`sed -n -e "${MAXLN}p" ffm.dat | awk '{printf("%12.0f"),$6}' | awk '{print $1}'`
        TDIP=`sed -n -e "${MAXLN}p" ffm.dat | awk '{printf("%12.0f"),$7}' | awk '{print $1}'`
        TRAK=`sed -n -e "${MAXLN}p" ffm.dat | awk '{printf("%12.0f"),$5}' |\
              awk '{if(0<$1&&$1<180||$1>360){print 90}else{print -90}}'`
        echo "Automatic target kinematics: $TSTR $TDIP $TRAK"
    else
        echo "Using target kinematics from command line: $TSTR $TDIP $TRAK"
    fi
    # Use peak slip location for reference point of dipping grid
    if [ -z $Z0 ]
    then
        LON0=`sed -n -e "${MAXLN}p" ffm.dat | awk '{printf("%12.2f"),$2}' | awk '{print $1}'`
        LAT0=`sed -n -e "${MAXLN}p" ffm.dat | awk '{printf("%12.2f"),$1}' | awk '{print $1}'`
        Z0=`sed -n -e "${MAXLN}p" ffm.dat | awk '{printf("%12.2f"),$3}' | awk '{print $1}'`
        echo "Using peak slip location as reference point: $LON0 $LAT0 $Z0"
    else
        echo "Using reference point from command line: $LON0 $LAT0 $Z0"
    fi
    STR0="$TSTR"
    DIP0="$TDIP"
else
    if [ -z $TRAK ]
    then
        TSTR=`awk '{print $4}' mt.dat`
        TDIP=`awk '{print $5}' mt.dat`
        TRAK=`awk '{print $6}' mt.dat | awk '{if($1>0){print 90}else{print -90}}'`
    else
        echo "Using target kinematics from command line: $TSTR $TDIP $TRAK"
    fi
    if [ -z $Z0 ]
    then
        Z0=`awk '{print $3}' mt.dat`
        LON0=`awk '{print $1}' mt.dat`
        LAT0=`awk '{print $2}' mt.dat`
    else
        echo "Using reference point from command line: $LON0 $LAT0 $Z"
    fi
    STR0="$TSTR"
    DIP0="$TDIP"
fi
FRIC="0.4"
echo $TSTR $TDIP $TRAK $FRIC > trg.dat

#####
#       SET UP COMPUTATION GRID
#####
if [ -z $LIMS ]
then
    # Use "-auto" option in O92UTIL to get rough map limits
    D="10"  # Test grid increment is large, to get map limits
    ZT="10"
    if [ $SRC_TYPE == "FFM" ]
    then
        o92util -ffm ffm.dat -auto h $ZT $D -haf haf.dat -disp disp.out > auto.dat
    else
        o92util -mag mt.dat -auto h $ZT $D -haf haf.dat -disp disp.out > auto.dat
    fi
    rm autosta.dat
    W=`grep " W: " auto.dat | awk '{print $2}'`
    E=`grep " E: " auto.dat | awk '{print $2}'`
    S=`grep " S: " auto.dat | awk '{print $2}'`
    N=`grep " N: " auto.dat | awk '{print $2}'`
    echo "Starting map limits: $W $E $S $N"
    
    # Determine if map has decent aspect ratio and correct as necessary
    # Mercator projection x and y lengths
    X=`echo $W $E | awk '{print $2-$1}'`
    Y=`echo $S $N |\
       awk '{
         v2 = log(sin(3.14159/4+$2/2*0.01745)/cos(3.14159/4+$2/2*0.01745))
         v1 = log(sin(3.14159/4+$1/2*0.01745)/cos(3.14159/4+$1/2*0.01745))
         print v2-v1
       }' |\
       awk '{print $1/0.017}'`
    # Check map aspect ratio (no skinnier than 1.4:1)
    FIX=`echo $X $Y |\
         awk '{
           if ($1>1.4*$2) {print "fixx"}
           else if ($2>1.4*$1) {print "fixy"}
           else {print 1}
         }'`
    # Reduce map limits in long dimension
    if [ $FIX == "fixx" ]
    then
        NEW=`echo $W $E $Y | awk '{print 0.5*($1+$2)-$3*0.70,0.5*($1+$2)+$3*0.70}'`
        W=`echo $NEW | awk '{print $1}'`
        E=`echo $NEW | awk '{print $2}'`
    elif [ $FIX == "fixy" ]
    then
        NEW=`echo $S $N $X $Y |\
             awk '{print 0.5*($1+$2)-0.7*$3/$4*($2-$1),0.5*($1+$2)+0.7*$3/$4*($2-$1)}'`
        S=`echo $NEW | awk '{print $1}'`
        N=`echo $NEW | awk '{print $2}'`
    fi
    # Round map limits to nearest 0.1
    W=`echo "$W\n$E" | gmtinfo -C -I0.1 | awk '{print $1}'`
    E=`echo "$W\n$E" | gmtinfo -C -I0.1 | awk '{print $2}'`
    S=`echo "$S\n$N" | gmtinfo -C -I0.1 | awk '{print $1}'`
    N=`echo "$S\n$N" | gmtinfo -C -I0.1 | awk '{print $2}'`
    echo "Final map limits:    $W $E $S $N"
else
    W=`echo $LIMS | sed -e "s/\// /g" -e "s/-R//" | awk '{print $1}'`
    E=`echo $LIMS | sed -e "s/\// /g" -e "s/-R//" | awk '{print $2}'`
    S=`echo $LIMS | sed -e "s/\// /g" -e "s/-R//" | awk '{print $3}'`
    N=`echo $LIMS | sed -e "s/\// /g" -e "s/-R//" | awk '{print $4}'`
    echo "Using map limits from command line: $W $E $S $N"
fi

# Create (NN x NN) point dipping grid
grid -x $W $E -nx $NN -y $S $N -ny $NN -dip $LON0 $LAT0 $Z0 $STR0 $DIP0 -o sta.dat

#####
#	COMPUTE COULOMB STRESS CHANGE
#####
if [ $SRC_TYPE == "FFM" ]
then
    o92util -ffm ffm.dat -sta sta.dat -haf haf.dat -trg trg.dat -coul coul.out -prog
else
    o92util -mag mt.dat -sta sta.dat -haf haf.dat -trg trg.dat -coul coul.out -prog -gmt rect.out
fi

#####
#	PLOT RESULTS
#####
PORTRAIT=`echo $X $Y | awk '{if($1<$2){print "-P"}}'`
PROJ="-JM5i $PORTRAIT"
LIMS="-R$W/$E/$S/$N"

# Colored grid of Coulomb stress changes
gmt makecpt -T-1e5/1e5/1e4 -C./no_green_mwh.cpt -D > coul.cpt
gmt makecpt -T-1e-1/1e-1/1e-2 -C./no_green_mwh.cpt -D > coul2.cpt
awk '{print $1,$2,$4}' coul.out | gmt xyz2grd -Gcoul.grd $LIMS -I$NN+/$NN+
gmt grdimage coul.grd $PROJ $LIMS -Ccoul.cpt -Y1.5i -K > $PSFILE
gmt psscale -D2.5i/-0.8i/5.0i/0.2ih -Ccoul2.cpt -Ba0.05 -Bg0.01 \
    -B+l"Coulomb Stress Change (MPa)" -Al -K -O >> $PSFILE

# Map stuff
ANNOT=`echo $W $E | awk '{if($2-$1<=10){print 1}else{print 2}}'`
gmt psbasemap $PROJ $LIMS -Bxa${ANNOT} -Bya1 -BWeSn -K -O --MAP_FRAME_TYPE=plain >> $PSFILE
gmt pscoast $PROJ $LIMS -Dh -W1p -G205/205/205 -N1/0.5p -K -O -t85 >> $PSFILE

# Plot FFM slip contours
if [ $SRC_TYPE == "FFM" ]
then
    if [ $SEG -eq 0 ]
    then
        ff2gmt -f ffm.dat -slip slip.out -clip clip.out
    else
        ff2gmt -f ffm.dat -slip slip.out -clipseg clip.out
    fi
    MAXSLIP=`awk '{print $3}' slip.out | gmtinfo -C | awk '{print $2}'`
    CONT=`echo $MAXSLIP |\
          awk '{
            if ($1>=50) {print 10}
            else if ($1>=20) {print 5}
            else if ($1>=10) {print 2}
            else if ($1>=2) {print 1}
            else {print 0.5}
          }'`
    echo $CONT $MAXSLIP | awk '{for (i=$1;i<=$2;i=i+$1){print i,"C"}}' > junk
    awk '{print $1,$2,$3}' slip.out |\
        gmt surface -Gslip.grd -I0.10/0.10 -Tb1 -Ti0.25 $LIMS
    gmt psclip clip.out $PROJ $LIMS -K -O >> $PSFILE
    gmt grdcontour slip.grd $PROJ $LIMS -W1p,white -Cjunk -K -O -t40 >> $PSFILE
    gmt psclip -C -K -O >> $PSFILE
    gmt psxy clip.out $PROJ $LIMS -W1p,white -K -O -t40 >> $PSFILE
    rm junk
else
    awk '{print $1,$2,$4,$5,$6}' rect.out |\
        gmt psxy $PROJ $LIMS -SJ -W1p,white -K -O -t40 >> $PSFILE
fi

# Plot epicenter
if [ $SRC_TYPE == "FFM" ]
then
    LONX=`sed -n -e "3p" ffm.dat | sed -e "s/.*Lon:/Lon:/" | awk '{print $2}'`
    LATX=`sed -n -e "3p" ffm.dat | sed -e "s/.*Lon:/Lon:/" | awk '{print $4}'`
    echo $LONX $LATX |\
        gmt psxy $PROJ $LIMS -Sa0.15i -W1p,black -K -O  >> $PSFILE
fi

# Legend (all coordinates are in cm from the bottom left)
LR=`echo $STR0 | awk '{if($1>180){print $1-360}else{print $1}}' |\
    awk '{if (-135<=$1&&$1<=90){print "L"}else{print "R"}}'`
X1="0.2"
X2="3.8"
Y1="0.2"
Y2="4.8"
XM=`echo $X1 $X2 | awk '{print 0.5*($1+$2)}'`
if [ $LR == "R" ]
then
    SHIFT=`echo $X2 | awk '{print 5-($1+0.2)/2.54}' | awk '{print "-X"$1"i"}'`
else
    SHIFT=""
fi
gmt psxy -JX10c -R0/10/0/10 -W1p -Gwhite $SHIFT -K -O >> $PSFILE << EOF
$X1 $Y1
$X1 $Y2
$X2 $Y2
$X2 $Y1
$X1 $Y1
EOF
LON0=`echo $LON0 | awk '{printf("%10.2f"),$1}' | awk '{print $1}'`
LAT0=`echo $LAT0 | awk '{printf("%10.2f"),$1}' | awk '{print $1}'`
Z0=`echo $Z0 | awk '{printf("%10.1f"),$1}' | awk '{print $1}'`
gmt pstext -JX10c -R0/10/0/10 -F+f+j -K -O >> $PSFILE << EOF
$XM 4.4 12,1 CM @_Target Faults@_
$XM 3.9 10,2 CM (On dipping surface)
$XM 3.5 10,0 CM Strike/Dip/Rake
$XM 3.1 10,0 CM $TSTR\260/$TDIP\260/$TRAK\260
$XM 2.6 10,0 CM Reference Point
$XM 2.2 10,0 CM ($LAT0\260N,$LON0\260E)
$XM 1.8 10,0 CM $Z0 km
EOF
if [ $SRC_TYPE == "FFM" ]
then
    if [ $LR == "R" ]
    then
        echo $X1 $Y1 $CONT |\
            awk '{
              if($3==1) {print $1-0.2,$2,"10,2 RB FFM Slip Contours: "$3" meter"}
              else      {print $1-0.2,$2,"10,2 RB FFM Slip Contours: "$3" meters"}
            }' |\
            gmt pstext -JX10c -R0/10/0/10 -F+f+j -N -K -O >> $PSFILE
    else
        echo $X2 $Y1 $CONT |\
            awk '{
              if($3==1) {print $1+0.2,$2,"10,2 LB FFM Slip Contours: "$3" meter"}
              else      {print $1+0.2,$2,"10,2 LB FFM Slip Contours: "$3" meters"}
            }' |\
            gmt pstext -JX10c -R0/10/0/10 -F+f+j -N -K -O >> $PSFILE
    fi
fi
# Schematic of target faults
XF="1.3"  # center of fault in x direction
YF="0.8"  # center of fault in y direction
LEN="1.0" # length of slip vector arrows
D="0.2"   # offset of slip vector arrows
FLT="0.8" # side length of square fault
SV=`echo $TSTR $TDIP $TRAK |\
    awk '{
      pi = 4*atan2(1,1)
      d2r = pi/180
      coss = cos((90-$1)*d2r)
      sins = sin((90-$1)*d2r)
      cosd = cos($2*d2r)
      sind = sin($2*d2r)
      cosr = cos($3*d2r)
      sinr = sin($3*d2r)
      x =  cosr*coss - sinr*cosd*sins
      y =  cosr*sins + sinr*cosd*coss
      z = sinr*sind
      print atan2(y,x)/d2r
    }'`
DX=`echo $TSTR $D | awk '{print $2*sin(($1+90)*0.01745)}'`
DY=`echo $TSTR $D | awk '{print $2*cos(($1+90)*0.01745)}'`
# Footwall slip vector
echo $DX $DY $SV $XF $YF $LEN |\
    awk '{print (-1)*$1+$4,(-1)*$2+$5,$3+180,$6}' |\
    gmt psxy -JX10c -R0/10/0/10 -Sv8p+e+jc+a45 -W1p -Gblack -K -O >> $PSFILE
# Fault square projected onto horizontal surface
echo $XF $YF $TSTR $FLT `echo $TDIP | awk '{print 0.7*cos($1*0.01745)}'` |\
    gmt psxy -JX10c -R0/10/0/10 -SJ -W1p,55/55/55 -Gwhite -K -O -t25 >> $PSFILE
# highlight updip edge of fault
echo $TSTR $TDIP $FLT $XF $YF |\
    awk '{
      d = $3*0.5
      print d*sin(($1-90)*0.01745)*cos($2*0.01745)+$4,
              d*cos(($1-90)*0.01745)*cos($2*0.01745)+$5,
                      $1,$3}' |\
    gmt psxy -JX10c -R0/10/0/10 -SV10p+jc -W2p,darkgreen -K -O -t25 >> $PSFILE
# Hanging wall slip vector
echo $DX $DY $SV $XF $YF $LEN |\
    awk '{print $1+$4,$2+$5,$3,$6}' |\
    gmt psxy -JX10c -R0/10/0/10 -Sv8p+e+jc+a45 -W1p -Gblack -K -O >> $PSFILE

XF="2.8"
echo $XF $YF 5 $TSTR $TDIP $TRAK 5 |\
    gmt psmeca -JX10c -R0/10/0/10 -Sa${FLT}c -G155/155/155 -K -O >> $PSFILE

echo 0 0 | gmt psxy $PROJ $LIMS -O >> $PSFILE


#####
#	CLEAN UP
#####
ps2pdf $PSFILE
rm no_green_mwh.cpt


